version: '3'
services:
  web:
    image: php:8.0-apache
    ports:
      - "8080:80"
    volumes:
      - ./cicekci:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=cicekci

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cicekci
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 